//! A silo's backup kept in a directory: a NAS share, an external drive, or
//! a folder a consumer sync client already syncs. Two devices writing here
//! never write the same file, which is the case sync clients handle well.
//! The asymmetry with putting a *silo* in such a folder: that shares one
//! snapshot file and produces conflict copies; sharing the log converges.

use std::path::{Component, Path, PathBuf};

use async_trait::async_trait;

use crate::{ObjectStore, StoreError, StoredObject};

pub struct FolderStore {
    root: PathBuf,
}

impl FolderStore {
    pub fn new(root: PathBuf) -> Self {
        Self { root }
    }

    /// Resolves a key to a path inside the root, refusing anything that
    /// climbs out of it.
    ///
    /// Keys are generated by this app and none of them contain `..` — but
    /// this is the one backend where a bad key becomes a write anywhere on
    /// the user's disk, so it is checked rather than assumed.
    fn path_for(&self, key: &str) -> Result<PathBuf, StoreError> {
        let relative = PathBuf::from(key.replace('\\', "/"));
        if relative
            .components()
            .any(|c| !matches!(c, Component::Normal(_)))
        {
            return Err(StoreError::Other(format!("refusing unsafe key: {key}")));
        }
        Ok(self.root.join(relative))
    }

    fn map_io(err: std::io::Error, what: &str) -> StoreError {
        match err.kind() {
            std::io::ErrorKind::NotFound => StoreError::NotFound(what.to_string()),
            std::io::ErrorKind::PermissionDenied => StoreError::Denied(err.to_string()),
            _ => StoreError::Other(err.to_string()),
        }
    }
}

#[async_trait]
impl ObjectStore for FolderStore {
    async fn put(&self, key: &str, body: Vec<u8>) -> Result<(), StoreError> {
        let path = self.path_for(key)?;
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(|e| Self::map_io(e, key))?;
        }

        // Written beside the target and renamed into place. A sync client
        // watching this folder must never see a half-written object — it
        // would upload the fragment, and another device would fetch bytes
        // that decrypt to nothing. Synced before the rename: a record is
        // marked delivered the moment this returns, and on a drive someone
        // then unplugs, renamed-but-unwritten is the same as lost.
        let temp = temp_beside(&path);
        {
            use std::io::Write;
            let mut file = std::fs::File::create(&temp).map_err(|e| Self::map_io(e, key))?;
            file.write_all(&body).map_err(|e| Self::map_io(e, key))?;
            file.sync_all().map_err(|e| Self::map_io(e, key))?;
        }
        silentsilo_core::rename_with_retry(&temp, &path).map_err(|e| Self::map_io(e, key))?;
        Ok(())
    }

    async fn put_from_file(&self, key: &str, source: &Path) -> Result<(), StoreError> {
        let path = self.path_for(key)?;
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(|e| Self::map_io(e, key))?;
        }
        let temp = temp_beside(&path);
        std::fs::copy(source, &temp).map_err(|e| Self::map_io(e, key))?;
        // Reopened with write access: Windows refuses to flush a read-only
        // handle.
        let copied = std::fs::OpenOptions::new()
            .write(true)
            .open(&temp)
            .map_err(|e| Self::map_io(e, key))?;
        copied.sync_all().map_err(|e| Self::map_io(e, key))?;
        silentsilo_core::rename_with_retry(&temp, &path).map_err(|e| Self::map_io(e, key))?;
        Ok(())
    }

    async fn get_to_file(&self, key: &str, dest: &Path) -> Result<(), StoreError> {
        std::fs::copy(self.path_for(key)?, dest)
            .map(|_| ())
            .map_err(|e| Self::map_io(e, key))
    }

    async fn get(&self, key: &str) -> Result<Vec<u8>, StoreError> {
        std::fs::read(self.path_for(key)?).map_err(|e| Self::map_io(e, key))
    }

    async fn head(&self, key: &str) -> Result<Option<i64>, StoreError> {
        match std::fs::metadata(self.path_for(key)?) {
            Ok(meta) => Ok(Some(meta.len() as i64)),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
            Err(e) => Err(Self::map_io(e, key)),
        }
    }

    async fn delete(&self, key: &str) -> Result<(), StoreError> {
        match std::fs::remove_file(self.path_for(key)?) {
            Ok(()) => Ok(()),
            // Deleting something already gone is the desired end state, and
            // callers use this to clean up after failures.
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
            Err(e) => Err(Self::map_io(e, key)),
        }
    }

    async fn list(&self, prefix: &str) -> Result<Vec<StoredObject>, StoreError> {
        let base = self.path_for(prefix.trim_end_matches('/'))?;
        let mut out = Vec::new();
        let mut seen = std::collections::HashSet::new();
        collect(&base, &self.root, &mut out, &mut seen)?;
        // Callers depend on this being ordered: operation keys are the
        // Lamport counter zero-padded, so sorting by key is sorting by time.
        // A filesystem promises nothing about readdir order.
        out.sort_by(|a, b| a.key.cmp(&b.key));
        Ok(out)
    }

    fn describe(&self) -> String {
        self.root.display().to_string()
    }
}

/// The temporary name a write goes to before its rename, always ending in
/// `.part` so listings can skip it.
fn temp_beside(path: &Path) -> PathBuf {
    path.with_extension(format!(
        "{}.part",
        path.extension().and_then(|e| e.to_str()).unwrap_or("tmp")
    ))
}

fn collect(
    dir: &Path,
    root: &Path,
    out: &mut Vec<StoredObject>,
    seen: &mut std::collections::HashSet<PathBuf>,
) -> Result<(), StoreError> {
    // A target is a directory the user chose, and it is theirs: it may hold
    // a symlink or a junction pointing back at an ancestor. `is_dir()`
    // follows those, so a listing walked in a circle until the stack ran
    // out. Descending only into directories not seen before is cheaper than
    // refusing links outright, which would skip the legitimate case of a
    // backup folder assembled out of mount points.
    //
    // A path that will not canonicalise is left to `read_dir` below rather
    // than treated as empty. "Could not look" and "looked and found
    // nothing" are the two answers it would be worst to confuse here: a
    // caller that reads an unreachable target as holding nothing carries on
    // and silently misses records.
    if let Ok(real) = std::fs::canonicalize(dir)
        && !seen.insert(real)
    {
        return Ok(());
    }

    let entries = match std::fs::read_dir(dir) {
        Ok(entries) => entries,
        // An absent prefix is an empty listing, not a failure — it is the
        // normal state of a bucket nothing has been written to yet.
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(e) => return Err(FolderStore::map_io(e, &dir.display().to_string())),
    };

    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(&path, root, out, seen)?;
            continue;
        }
        // A rename that never completed, or a sync client's own scratch.
        // Reporting it as an object would hand the caller a partial file.
        if path.extension().and_then(|e| e.to_str()) == Some("part") {
            continue;
        }
        let Ok(relative) = path.strip_prefix(root) else {
            continue;
        };
        let size = path.metadata().map(|m| m.len() as i64).unwrap_or(0);
        out.push(StoredObject {
            key: relative.to_string_lossy().replace('\\', "/"),
            size,
        });
    }
    Ok(())
}
