//! A silo's backup on a WebDAV share (Nextcloud, Synology, most NAS
//! boxes). Two things are not ordinary HTTP and are where the work is:
//! collections are not implicit, so parents are created before every PUT;
//! and `href`s come back in the server's own dialect, so normalising them
//! back to our keys is the fiddly part.

use async_trait::async_trait;
use quick_xml::Reader;
use quick_xml::events::Event;
use reqwest::{Client, Method, StatusCode};

use crate::{ObjectStore, StoreError, StoredObject};

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct WebDavConfig {
    /// The collection the silo lives in, e.g.
    /// `https://cloud.example.com/remote.php/dav/files/alex/silentsilo`.
    pub url: String,
    pub username: String,
    pub password: String,
}

pub struct WebDavStore {
    client: Client,
    /// Collections already created in this session.
    ///
    /// Without it every `put` costs an extra round trip to `MKCOL` a
    /// collection that has existed since the first one — which on a sync
    /// pass of a thousand operations is a thousand pointless requests.
    known_collections: std::sync::Mutex<std::collections::HashSet<String>>,
    /// Always with a trailing slash, so joining a key is concatenation.
    base: String,
    /// The path part of `base`, for stripping off returned hrefs.
    base_path: String,
    username: String,
    password: String,
}

impl WebDavStore {
    pub fn new(config: WebDavConfig) -> Result<Self, StoreError> {
        let url = config.url.trim().trim_end_matches('/').to_string();
        if !url.starts_with("http://") && !url.starts_with("https://") {
            return Err(StoreError::Other(
                "the WebDAV address must start with https:// (or http:// on a local network)"
                    .into(),
            ));
        }
        let parsed =
            url::Url::parse(&url).map_err(|e| StoreError::Other(format!("bad address: {e}")))?;

        Ok(Self {
            client: Client::builder()
                .build()
                .map_err(|e| StoreError::Other(e.to_string()))?,
            known_collections: std::sync::Mutex::new(std::collections::HashSet::new()),
            base_path: format!("{}/", parsed.path().trim_end_matches('/')),
            base: format!("{url}/"),
            username: config.username,
            password: config.password,
        })
    }

    fn url_for(&self, key: &str) -> String {
        // The key is generated by this app and contains only path-safe
        // characters, but percent-encoding it costs nothing and means a
        // future key with a space in it does not silently become two.
        let encoded = key
            .split('/')
            .map(|segment| {
                percent_encoding::utf8_percent_encode(segment, percent_encoding::NON_ALPHANUMERIC)
                    .to_string()
            })
            .collect::<Vec<_>>()
            .join("/");
        format!("{}{encoded}", self.base)
    }

    fn request(&self, method: Method, url: &str) -> reqwest::RequestBuilder {
        self.client
            .request(method, url)
            .basic_auth(&self.username, Some(&self.password))
    }

    fn map_status(status: StatusCode, what: &str) -> StoreError {
        match status {
            StatusCode::NOT_FOUND => StoreError::NotFound(what.to_string()),
            StatusCode::UNAUTHORIZED | StatusCode::FORBIDDEN => {
                StoreError::Denied(format!("{status} for {what}"))
            }
            _ => StoreError::Other(format!("{status} for {what}")),
        }
    }

    fn map_send(err: reqwest::Error) -> StoreError {
        if err.is_timeout() || err.is_connect() {
            StoreError::Unreachable(err.to_string())
        } else {
            StoreError::Other(err.to_string())
        }
    }

    /// Creates one collection if it isn't already there.
    ///
    /// `MKCOL` on an existing collection answers 405, which is success here
    /// — the goal is that it exists, not that we made it. A 409 is *not*
    /// tolerated: it means the parent is missing, which since these are
    /// created outermost-first would be a real structural problem rather
    /// than a race.
    async fn ensure_collection(&self, path: &str, url: &str) -> Result<(), StoreError> {
        if self
            .known_collections
            .lock()
            .map(|seen| seen.contains(path))
            .unwrap_or(false)
        {
            return Ok(());
        }

        let response = self
            .request(Method::from_bytes(b"MKCOL").unwrap(), url)
            .send()
            .await
            .map_err(Self::map_send)?;
        let status = response.status();
        if !status.is_success() && status != StatusCode::METHOD_NOT_ALLOWED {
            return Err(Self::map_status(status, path));
        }

        if let Ok(mut seen) = self.known_collections.lock() {
            seen.insert(path.to_string());
        }
        Ok(())
    }

    /// Creates every collection a key needs, outermost first.
    ///
    /// Including the base itself. The user points us at a collection that
    /// usually exists, but "usually" is not a contract — and a `PUT` into a
    /// missing collection answers 403 or 409, which reads as a permissions
    /// problem and sends people to check credentials that were fine.
    async fn ensure_parents(&self, key: &str) -> Result<(), StoreError> {
        self.ensure_collection("", self.base.trim_end_matches('/'))
            .await?;

        let mut prefix = String::new();
        let segments: Vec<&str> = key.split('/').collect();
        for segment in &segments[..segments.len().saturating_sub(1)] {
            prefix.push_str(segment);
            let url = self.url_for(&prefix);
            self.ensure_collection(&prefix, &url).await?;
            prefix.push('/');
        }
        Ok(())
    }
}

#[async_trait]
impl ObjectStore for WebDavStore {
    async fn put(&self, key: &str, body: Vec<u8>) -> Result<(), StoreError> {
        self.ensure_parents(key).await?;
        let response = self
            .request(Method::PUT, &self.url_for(key))
            .body(body)
            .send()
            .await
            .map_err(Self::map_send)?;
        if !response.status().is_success() {
            return Err(Self::map_status(response.status(), key));
        }
        Ok(())
    }

    async fn get(&self, key: &str) -> Result<Vec<u8>, StoreError> {
        let response = self
            .request(Method::GET, &self.url_for(key))
            .send()
            .await
            .map_err(Self::map_send)?;
        if !response.status().is_success() {
            return Err(Self::map_status(response.status(), key));
        }
        Ok(response.bytes().await.map_err(Self::map_send)?.to_vec())
    }

    async fn head(&self, key: &str) -> Result<Option<i64>, StoreError> {
        let response = self
            .request(Method::HEAD, &self.url_for(key))
            .send()
            .await
            .map_err(Self::map_send)?;
        if response.status() == StatusCode::NOT_FOUND {
            return Ok(None);
        }
        if !response.status().is_success() {
            return Err(Self::map_status(response.status(), key));
        }
        Ok(Some(
            response
                .headers()
                .get(reqwest::header::CONTENT_LENGTH)
                .and_then(|v| v.to_str().ok())
                .and_then(|v| v.parse().ok())
                .unwrap_or(0),
        ))
    }

    async fn delete(&self, key: &str) -> Result<(), StoreError> {
        let response = self
            .request(Method::DELETE, &self.url_for(key))
            .send()
            .await
            .map_err(Self::map_send)?;
        // Already gone is the desired end state: callers use this to clean
        // up after failures that may never have written anything.
        if response.status().is_success() || response.status() == StatusCode::NOT_FOUND {
            return Ok(());
        }
        Err(Self::map_status(response.status(), key))
    }

    async fn list(&self, prefix: &str) -> Result<Vec<StoredObject>, StoreError> {
        // `Depth: infinity` would save the recursion, but Apache's mod_dav
        // refuses it by default and several NAS servers follow suit. One
        // level at a time works everywhere, and the trees here are two deep.
        let mut out = Vec::new();
        let mut queue = vec![prefix.trim_end_matches('/').to_string()];

        while let Some(collection) = queue.pop() {
            let response = self
                .request(
                    Method::from_bytes(b"PROPFIND").unwrap(),
                    &self.url_for(&collection),
                )
                .header("Depth", "1")
                .header("Content-Type", "application/xml")
                .body(
                    r#"<?xml version="1.0"?>
<d:propfind xmlns:d="DAV:"><d:prop>
  <d:getcontentlength/><d:resourcetype/>
</d:prop></d:propfind>"#,
                )
                .send()
                .await
                .map_err(Self::map_send)?;

            // A prefix nothing has been written to yet is an empty listing,
            // not a failure — the normal state of fresh storage.
            if response.status() == StatusCode::NOT_FOUND {
                continue;
            }
            if !response.status().is_success() {
                return Err(Self::map_status(response.status(), &collection));
            }

            let body = response.text().await.map_err(Self::map_send)?;
            for entry in parse_multistatus(&body, &self.base_path)? {
                // A PROPFIND includes the collection it was asked about.
                if entry.key == collection || entry.key.is_empty() {
                    continue;
                }
                if entry.is_collection {
                    queue.push(entry.key);
                } else {
                    out.push(StoredObject {
                        key: entry.key,
                        size: entry.size,
                    });
                }
            }
        }

        // Operation keys are the Lamport counter zero-padded, so callers
        // read this order as chronological. A server's own order is not
        // specified.
        out.sort_by(|a, b| a.key.cmp(&b.key));
        Ok(out)
    }

    fn describe(&self) -> String {
        self.base.trim_end_matches('/').to_string()
    }
}

struct DavEntry {
    key: String,
    size: i64,
    is_collection: bool,
}

/// Pulls the hrefs, sizes and collection flags out of a multistatus body.
///
/// Deliberately tolerant: servers differ in namespace prefix (`d:`, `D:`,
/// none), in whether hrefs are absolute or path-only, and in whether they
/// percent-encode characters that did not need it. Matching on local names
/// and normalising the href is what makes one implementation work against
/// Nextcloud, Apache and a Synology alike.
fn parse_multistatus(xml: &str, base_path: &str) -> Result<Vec<DavEntry>, StoreError> {
    let mut reader = Reader::from_str(xml);
    reader.config_mut().trim_text(true);

    let mut entries = Vec::new();
    let mut current: Option<DavEntry> = None;
    let mut field: Option<&'static str> = None;

    loop {
        match reader.read_event() {
            Ok(Event::Start(e)) => match local_name(e.name().as_ref()) {
                "response" => {
                    current = Some(DavEntry {
                        key: String::new(),
                        size: 0,
                        is_collection: false,
                    })
                }
                "href" => field = Some("href"),
                "getcontentlength" => field = Some("size"),
                // `<collection/>` is usually empty, so it arrives as an
                // Empty event — but some servers emit it with whitespace.
                "collection" => {
                    if let Some(entry) = current.as_mut() {
                        entry.is_collection = true;
                    }
                }
                _ => {}
            },
            Ok(Event::Empty(e)) => {
                if local_name(e.name().as_ref()) == "collection"
                    && let Some(entry) = current.as_mut()
                {
                    entry.is_collection = true;
                }
            }
            Ok(Event::Text(e)) => {
                let raw = e.decode().unwrap_or_default().to_string();
                // Hrefs are percent-encoded, so the only XML entities that
                // realistically appear are `&amp;` in a path — decoded here
                // rather than left to become a literal "&amp;" in a key.
                let text = raw
                    .replace("&amp;", "&")
                    .replace("&lt;", "<")
                    .replace("&gt;", ">")
                    .replace("&quot;", "\"")
                    .replace("&apos;", "'");
                match (field, current.as_mut()) {
                    (Some("href"), Some(entry)) => entry.key = normalise_href(&text, base_path),
                    (Some("size"), Some(entry)) => entry.size = text.parse().unwrap_or(0),
                    _ => {}
                }
                field = None;
            }
            Ok(Event::End(e)) => {
                if local_name(e.name().as_ref()) == "response"
                    && let Some(entry) = current.take()
                {
                    entries.push(entry);
                }
                field = None;
            }
            Ok(Event::Eof) => break,
            Err(e) => return Err(StoreError::Other(format!("unreadable WebDAV reply: {e}"))),
            _ => {}
        }
    }
    Ok(entries)
}

/// The element's name without whatever namespace prefix the server chose.
///
/// Servers use `d:`, `D:`, or no prefix at all, so matching on the local
/// name is what lets one parser handle Nextcloud, Apache and a Synology.
fn local_name(raw: &[u8]) -> &'static str {
    let local = match raw.iter().position(|b| *b == b':') {
        Some(i) => &raw[i + 1..],
        None => raw,
    };
    match local {
        b"response" => "response",
        b"href" => "href",
        b"getcontentlength" => "getcontentlength",
        b"collection" => "collection",
        _ => "",
    }
}

/// Turns a server's href back into one of our keys.
fn normalise_href(href: &str, base_path: &str) -> String {
    // Absolute URLs are allowed here, and Nextcloud uses them.
    let path = match href.find("://") {
        Some(i) => match href[i + 3..].find('/') {
            Some(j) => &href[i + 3 + j..],
            None => "",
        },
        None => href,
    };
    let decoded = percent_encoding::percent_decode_str(path)
        .decode_utf8_lossy()
        .to_string();
    decoded
        .strip_prefix(base_path)
        .unwrap_or_else(|| decoded.trim_start_matches('/'))
        .trim_end_matches('/')
        .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn an_absolute_href_is_reduced_to_a_key() {
        // Nextcloud answers with the full URL and the share's mount path.
        assert_eq!(
            normalise_href(
                "https://cloud.example.com/remote.php/dav/files/alex/silo/ops/000001.op",
                "/remote.php/dav/files/alex/silo/"
            ),
            "ops/000001.op"
        );
    }

    #[test]
    fn a_path_only_href_is_reduced_to_a_key() {
        // Apache's mod_dav answers with just the path.
        assert_eq!(
            normalise_href("/silo/blobs/a.sslo", "/silo/"),
            "blobs/a.sslo"
        );
    }

    #[test]
    fn a_percent_encoded_href_is_decoded() {
        assert_eq!(
            normalise_href("/silo/ops/my%20file.op", "/silo/"),
            "ops/my file.op"
        );
    }

    #[test]
    fn a_collections_trailing_slash_is_dropped() {
        // Otherwise the recursion would ask about "ops/" and compare it
        // against "ops", and never notice it had already been there.
        assert_eq!(normalise_href("/silo/ops/", "/silo/"), "ops");
    }

    #[test]
    fn the_namespace_prefix_does_not_matter() {
        // `d:`, `D:`, and none are all in the wild.
        for xml in [
            r#"<d:multistatus xmlns:d="DAV:"><d:response><d:href>/s/a.op</d:href><d:propstat><d:prop><d:getcontentlength>12</d:getcontentlength></d:prop></d:propstat></d:response></d:multistatus>"#,
            r#"<D:multistatus xmlns:D="DAV:"><D:response><D:href>/s/a.op</D:href><D:propstat><D:prop><D:getcontentlength>12</D:getcontentlength></D:prop></D:propstat></D:response></D:multistatus>"#,
            r#"<multistatus xmlns="DAV:"><response><href>/s/a.op</href><propstat><prop><getcontentlength>12</getcontentlength></prop></propstat></response></multistatus>"#,
        ] {
            let entries = parse_multistatus(xml, "/s/").unwrap();
            assert_eq!(entries.len(), 1, "failed on {xml}");
            assert_eq!(entries[0].key, "a.op");
            assert_eq!(entries[0].size, 12);
            assert!(!entries[0].is_collection);
        }
    }

    #[test]
    fn a_collection_is_recognised_whether_or_not_it_is_self_closing() {
        for body in ["<d:collection/>", "<d:collection></d:collection>"] {
            let xml = format!(
                r#"<d:multistatus xmlns:d="DAV:"><d:response><d:href>/s/ops/</d:href>
                <d:propstat><d:prop><d:resourcetype>{body}</d:resourcetype></d:prop></d:propstat>
                </d:response></d:multistatus>"#
            );
            let entries = parse_multistatus(&xml, "/s/").unwrap();
            assert!(entries[0].is_collection, "failed on {body}");
            assert_eq!(entries[0].key, "ops");
        }
    }

    #[test]
    fn a_reply_with_several_responses_yields_them_all() {
        let xml = r#"<d:multistatus xmlns:d="DAV:">
          <d:response><d:href>/s/ops/</d:href><d:propstat><d:prop><d:resourcetype><d:collection/></d:resourcetype></d:prop></d:propstat></d:response>
          <d:response><d:href>/s/ops/000001.op</d:href><d:propstat><d:prop><d:getcontentlength>7</d:getcontentlength></d:prop></d:propstat></d:response>
          <d:response><d:href>/s/ops/000002.op</d:href><d:propstat><d:prop><d:getcontentlength>9</d:getcontentlength></d:prop></d:propstat></d:response>
        </d:multistatus>"#;
        let entries = parse_multistatus(xml, "/s/").unwrap();
        assert_eq!(entries.len(), 3);
        assert_eq!(entries.iter().filter(|e| e.is_collection).count(), 1);
    }

    #[test]
    fn an_address_without_a_scheme_is_refused_before_anything_is_sent() {
        let Err(err) = WebDavStore::new(WebDavConfig {
            url: "cloud.example.com/dav".into(),
            username: "a".into(),
            password: "b".into(),
        }) else {
            panic!("an address with no scheme must be refused");
        };
        assert!(err.to_string().contains("https://"), "got: {err}");
    }
}
